/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.bmuskalla.system.properties;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
