/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.bmuskalla.system.properties;

public class ScopedSystemProperties {

    public static SystemPropertyScope scoped() {
        return new SystemPropertyScope() {

        };
    }

    private ScopedSystemProperties() {
        // prevent direct instantiation
    }

}
